<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <PackageId>Orion.API.ChatApi</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="15.0.1" />
        <PackageReference Include="Azure.AI.Agents.Persistent" Version="1.1.0" />
        <PackageReference Include="Azure.AI.Projects" Version="1.0.0-beta.10" />
        <PackageReference Include="Azure.Identity" Version="1.15.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="9.0.7" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.9" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />

    </ItemGroup>



    <ItemGroup>
      <Content Remove="Data\**" />
    </ItemGroup>



    <ItemGroup>
      <ProjectReference Include="..\..\DataAccess\Orion.DataAccess.Postgres\Orion.DataAccess.Postgres.csproj" />
      <ProjectReference Include="..\..\Helpers\Orion.Helpers.csproj" />
    </ItemGroup>



    <ItemGroup>
      <Compile Remove="Data\**" />
    </ItemGroup>



    <ItemGroup>
      <EmbeddedResource Remove="Data\**" />
    </ItemGroup>



    <ItemGroup>
      <None Remove="Data\**" />
    </ItemGroup>

</Project>
