//using System;
//using System.Collections.Generic;
//using System.Linq;

//namespace Orion.WebApps.AanalysisDashboard.Models
//{
//    /// <summary>
//    /// Represents a trading signal generated by the system with comprehensive trade parameters
//    /// </summary>
//    public sealed class TradingOpportunity
//    {
//        private readonly List<SignalReason> _reasons = new();
//        private readonly Dictionary<Timeframe, TimeframeSignal> _timeframeSignals = new();

//        /// <summary>
//        /// Unique identifier for the signal
//        /// </summary>
//        public string Id { get; } = Guid.NewGuid().ToString("N");

//        /// <summary>
//        /// Timestamp when the signal was generated
//        /// </summary>
//        public DateTime GeneratedAt { get; } = DateTime.UtcNow;

//        /// <summary>
//        /// Trading pair symbol (e.g., EUR/USD)
//        /// </summary>
//        public string Pair { get; init; } = string.Empty;

//        /// <summary>
//        /// Current price at signal generation
//        /// </summary>
//        public decimal CurrentPrice { get; init; }

//        /// <summary>
//        /// Trading direction (Long/Short)
//        /// </summary>
//        public TradeDirection Direction { get; init; }

//        /// <summary>
//        /// Signal conviction level
//        /// </summary>
//        public ConvictionLevel Conviction { get; init; }

//        /// <summary>
//        /// Composite strength score (0-100)
//        /// </summary>
//        public int StrengthScore { get; init; }

//        /// <summary>
//        /// Trading thesis explaining the signal rationale
//        /// </summary>
//        public string Thesis { get; init; } = string.Empty;

//        /// <summary>
//        /// Entry price level
//        /// </summary>
//        public decimal EntryPrice { get; init; }

//        /// <summary>
//        /// Stop loss price level
//        /// </summary>
//        public decimal StopLossPrice { get; init; }

//        /// <summary>
//        /// Primary take profit level
//        /// </summary>
//        public decimal TakeProfit1Price { get; init; }

//        /// <summary>
//        /// Secondary take profit level
//        /// </summary>
//        public decimal TakeProfit2Price { get; init; }

//        /// <summary>
//        /// Risk/Reward ratio for primary target
//        /// </summary>
//        public decimal RiskRewardRatio { get; init; }

//        /// <summary>
//        /// RSI value at signal generation
//        /// </summary>
//        public decimal? RsiValue { get; init; }

//        /// <summary>
//        /// ATR value for volatility measurement
//        /// </summary>
//        public decimal? AtrValue { get; init; }

//        /// <summary>
//        /// Number of timeframes confirming the signal
//        /// </summary>
//        public int ConfirmingTimeframes { get; init; }

//        /// <summary>
//        /// Primary timeframe that generated the signal
//        /// </summary>
//        public Timeframe PrimaryTimeframe { get; init; }

//        /// <summary>
//        /// Entry signal details if applicable
//        /// </summary>
//        public EntrySignal? EntrySignalDetails { get; init; }

//        /// <summary>
//        /// Read-only collection of reasons supporting the signal
//        /// </summary>
//        public IReadOnlyList<SignalReason> Reasons => _reasons.AsReadOnly();

//        /// <summary>
//        /// Read-only dictionary of signals per timeframe
//        /// </summary>
//        public IReadOnlyDictionary<Timeframe, TimeframeSignal> TimeframeSignals => _timeframeSignals;

//        /// <summary>
//        /// Position size recommendation (as percentage of account)
//        /// </summary>
//        public decimal RecommendedPositionSize { get; init; }

//        /// <summary>
//        /// Expected holding period
//        /// </summary>
//        public TimeSpan ExpectedHoldingPeriod { get; init; }

//        /// <summary>
//        /// Signal expiration time
//        /// </summary>
//        public DateTime ExpiresAt { get; init; }

//        /// <summary>
//        /// Whether the signal is still valid
//        /// </summary>
//        public bool IsValid =>
//            Direction != TradeDirection.Neutral &&
//            EntryPrice > 0 &&
//            StopLossPrice > 0 &&
//            DateTime.UtcNow < ExpiresAt &&
//            ValidatePriceLevels();

//        /// <summary>
//        /// Whether the signal has high conviction
//        /// </summary>
//        public bool IsHighConviction => Conviction >= ConvictionLevel.High;

//        /// <summary>
//        /// Risk percentage of account
//        /// </summary>
//        public decimal RiskPercentage =>
//            Direction == TradeDirection.Long
//                ? ((EntryPrice - StopLossPrice) / EntryPrice) * 100
//                : ((StopLossPrice - EntryPrice) / EntryPrice) * 100;

//        /// <summary>
//        /// Potential profit percentage for primary target
//        /// </summary>
//        public decimal PotentialProfitPercentage =>
//            Direction == TradeDirection.Long
//                ? ((TakeProfit1Price - EntryPrice) / EntryPrice) * 100
//                : ((EntryPrice - TakeProfit1Price) / EntryPrice) * 100;
        

//        /// <summary>
//        /// Creates a new trading signal using the builder pattern
//        /// </summary>
//        public static TradingSignalBuilder CreateBuilder() => new();

//        /// <summary>
//        /// Adds a reason to the signal
//        /// </summary>
//        internal void AddReason(SignalReason reason) => _reasons.Add(reason);

//        /// <summary>
//        /// Adds a timeframe signal
//        /// </summary>
//        internal void AddTimeframeSignal(Timeframe timeframe, TimeframeSignal signal)
//            => _timeframeSignals[timeframe] = signal;

//        /// <summary>
//        /// Validates price levels for logical consistency
//        /// </summary>
//        private bool ValidatePriceLevels()
//        {
//            return Direction switch
//            {
//                TradeDirection.Long =>
//                    EntryPrice > StopLossPrice &&
//                    TakeProfit1Price > EntryPrice,

//                TradeDirection.Short =>
//                    StopLossPrice > EntryPrice &&
//                    EntryPrice > TakeProfit1Price,

//                _ => false
//            };
//        }

//        /// <summary>
//        /// Calculates the position size in lots based on account size and risk percentage
//        /// </summary>
//        public decimal CalculatePositionSize(decimal accountBalance, decimal riskPerTrade)
//        {
//            var riskAmount = accountBalance * (riskPerTrade / 100);
//            var pipRisk = Math.Abs(EntryPrice - StopLossPrice);

//            return pipRisk > 0 ? riskAmount / pipRisk : 0;
//        }

//        /// <summary>
//        /// Gets the signal as a formatted string
//        /// </summary>
//        public override string ToString()
//        {
//            var direction = Direction == TradeDirection.Long ? "📈 LONG" : "📉 SHORT";
//            var conviction = Conviction.ToString().ToUpper();
//            var tfInfo = ConfirmingTimeframes > 0 ? $" ({ConfirmingTimeframes} TFs)" : "";

//            return $"{Pair}: {direction} [{conviction}]{tfInfo} | " +
//                   $"Entry: {EntryPrice:F4} | SL: {StopLossPrice:F4} | " +
//                   $"R:R 1:{RiskRewardRatio:F2} | Score: {StrengthScore}/100";
//        }

//        /// <summary>
//        /// Gets a detailed analysis of the signal
//        /// </summary>
//        public string GetDetailedAnalysis()
//        {
//            var lines = new List<string>
//        {
//            ToString(),
//            $"Thesis: {Thesis}",
//            $"Price: {CurrentPrice:F4} | RSI: {RsiValue:F1} | ATR: {AtrValue:F4}",
//            $"Risk: {RiskPercentage:F2}% | Reward: {PotentialProfitPercentage:F2}%",
//            $"Position Size: {RecommendedPositionSize:F2}%",
//            "Supporting Factors:"
//        };

//            lines.AddRange(Reasons.Select(r => $"  • {r.Description} (Weight: {r.Weight})"));

//            return string.Join(Environment.NewLine, lines);
//        }
//    }

//    /// <summary>
//    /// Builder class for creating TradingSignal instances
//    /// </summary>
//    public class TradingSignalBuilder
//    {
//        private readonly TradingSignal _signal = new();

//        public TradingSignalBuilder WithPair(string pair)
//        {
//            _signal.Pair = pair;
//            return this;
//        }

//        public TradingSignalBuilder WithCurrentPrice(decimal price)
//        {
//            _signal.CurrentPrice = price;
//            return this;
//        }

//        public TradingSignalBuilder WithDirection(TradeDirection direction)
//        {
//            _signal.Direction = direction;
//            return this;
//        }

//        public TradingSignalBuilder WithConviction(ConvictionLevel conviction)
//        {
//            _signal.Conviction = conviction;
//            return this;
//        }

//        public TradingSignalBuilder WithStrengthScore(int score)
//        {
//            _signal.StrengthScore = Math.Clamp(score, 0, 100);
//            return this;
//        }

//        public TradingSignalBuilder WithThesis(string thesis)
//        {
//            _signal.Thesis = thesis;
//            return this;
//        }

//        public TradingSignalBuilder WithEntryPrice(decimal entry)
//        {
//            _signal.EntryPrice = entry;
//            return this;
//        }

//        public TradingSignalBuilder WithStopLoss(decimal stopLoss)
//        {
//            _signal.StopLossPrice = stopLoss;
//            return this;
//        }

//        public TradingSignalBuilder WithTakeProfit1(decimal tp1)
//        {
//            _signal.TakeProfit1Price = tp1;
//            return this;
//        }

//        public TradingSignalBuilder WithTakeProfit2(decimal tp2)
//        {
//            _signal.TakeProfit2Price = tp2;
//            return this;
//        }

//        public TradingSignalBuilder WithRiskRewardRatio(decimal ratio)
//        {
//            _signal.RiskRewardRatio = ratio;
//            return this;
//        }

//        public TradingSignalBuilder WithRsi(decimal? rsi)
//        {
//            _signal.RsiValue = rsi;
//            return this;
//        }

//        public TradingSignalBuilder WithAtr(decimal? atr)
//        {
//            _signal.AtrValue = atr;
//            return this;
//        }

//        public TradingSignalBuilder WithConfirmingTimeframes(int count)
//        {
//            _signal.ConfirmingTimeframes = count;
//            return this;
//        }

//        public TradingSignalBuilder WithPrimaryTimeframe(Timeframe timeframe)
//        {
//            _signal.PrimaryTimeframe = timeframe;
//            return this;
//        }

//        public TradingSignalBuilder WithEntrySignal(EntrySignal entrySignal)
//        {
//            _signal.EntrySignalDetails = entrySignal;
//            return this;
//        }

//        public TradingSignalBuilder WithRecommendedPositionSize(decimal size)
//        {
//            _signal.RecommendedPositionSize = size;
//            return this;
//        }

//        public TradingSignalBuilder WithExpectedHoldingPeriod(TimeSpan period)
//        {
//            _signal.ExpectedHoldingPeriod = period;
//            return this;
//        }

//        public TradingSignalBuilder WithExpiration(DateTime expiration)
//        {
//            _signal.ExpiresAt = expiration;
//            return this;
//        }

//        public TradingSignalBuilder AddReason(string description, int weight, SignalCategory category)
//        {
//            _signal.AddReason(new SignalReason(description, weight, category));
//            return this;
//        }

//        public TradingSignalBuilder AddTimeframeSignal(Timeframe timeframe, TimeframeSignal signal)
//        {
//            _signal.AddTimeframeSignal(timeframe, signal);
//            return this;
//        }

//        /// <summary>
//        /// Automatically calculates R:R ratio based on price levels
//        /// </summary>
//        public TradingSignalBuilder CalculateRiskReward()
//        {
//            if (_signal.EntryPrice > 0 && _signal.StopLossPrice > 0 && _signal.TakeProfit1Price > 0)
//            {
//                var risk = Math.Abs(_signal.EntryPrice - _signal.StopLossPrice);
//                var reward = Math.Abs(_signal.TakeProfit1Price - _signal.EntryPrice);

//                _signal.RiskRewardRatio = risk > 0 ? reward / risk : 0;
//            }
//            return this;
//        }

//        /// <summary>
//        /// Builds and validates the TradingSignal
//        /// </summary>
//        public TradingSignal Build()
//        {
//            // Set default expiration if not specified (24 hours)
//            if (_signal.ExpiresAt == default)
//            {
//                _signal.ExpiresAt = DateTime.UtcNow.AddHours(24);
//            }

//            // Validate required fields
//            Validate();

//            return _signal;
//        }

//        private void Validate()
//        {
//            var errors = new List<string>();

//            if (string.IsNullOrWhiteSpace(_signal.Pair))
//                errors.Add("Pair is required");

//            if (_signal.Direction == TradeDirection.Neutral)
//                errors.Add("Trade direction must be specified");

//            if (_signal.EntryPrice <= 0)
//                errors.Add("Entry price must be greater than 0");

//            if (_signal.StopLossPrice <= 0)
//                errors.Add("Stop loss must be greater than 0");

//            if (_signal.TakeProfit1Price <= 0)
//                errors.Add("Take profit must be greater than 0");

//            if (errors.Any())
//                throw new InvalidOperationException($"Invalid trading signal: {string.Join(", ", errors)}");
//        }
//    }

//    /// <summary>
//    /// Represents a reason supporting the trading signal
//    /// </summary>
//    public sealed record SignalReason
//    {
//        public string Description { get; }
//        public int Weight { get; }
//        public SignalCategory Category { get; }
//        public DateTime Timestamp { get; }

//        public SignalReason(string description, int weight, SignalCategory category)
//        {
//            Description = description ?? throw new ArgumentNullException(nameof(description));
//            Weight = weight;
//            Category = category;
//            Timestamp = DateTime.UtcNow;
//        }
//    }

//    /// <summary>
//    /// Signal specific to a particular timeframe
//    /// </summary>
//    public sealed record TimeframeSignal
//    {
//        public Timeframe Timeframe { get; init; }
//        public TradeDirection Direction { get; init; }
//        public int StrengthScore { get; init; }
//        public decimal? Rsi { get; init; }
//        public decimal? Atr { get; init; }
//        public string Analysis { get; init; } = string.Empty;
//    }

//    /// <summary>
//    /// Entry signal details for precise trade execution
//    /// </summary>
//    public sealed record EntrySignal
//    {
//        public EntrySignalType Type { get; init; }
//        public decimal TriggerPrice { get; init; }
//        public string Description { get; init; } = string.Empty;
//        public DateTime? ValidUntil { get; init; }
//    }

//    /// <summary>
//    /// Extension methods for TradingSignal
//    /// </summary>
//    public static class TradingSignalExtensions
//    {
//        /// <summary>
//        /// Determines if the signal is appropriate for a given risk profile
//        /// </summary>
//        public static bool IsSuitableForRiskProfile(this TradingSignal signal, RiskProfile profile)
//        {
//            return profile switch
//            {
//                RiskProfile.Conservative =>
//                    signal.Conviction >= ConvictionLevel.High &&
//                    signal.RiskRewardRatio >= 3,

//                RiskProfile.Moderate =>
//                    signal.Conviction >= ConvictionLevel.Medium &&
//                    signal.RiskRewardRatio >= 2,

//                RiskProfile.Aggressive =>
//                    signal.RiskRewardRatio >= 1.5m,

//                _ => false
//            };
//        }

//        /// <summary>
//        /// Gets the signal strength as a descriptive category
//        /// </summary>
//        public static string GetStrengthCategory(this TradingSignal signal)
//        {
//            return signal.StrengthScore switch
//            {
//                >= 80 => "Very Strong",
//                >= 60 => "Strong",
//                >= 40 => "Moderate",
//                >= 20 => "Weak",
//                _ => "Very Weak"
//            };
//        }
//    }

//    /// <summary>
//    /// Type of entry signal
//    /// </summary>
//    public enum EntrySignalType
//    {
//        Breakout = 1,
//        Pullback = 2,
//        Reversal = 3,
//        Continuation = 4,
//        SupportBounce = 5,
//        ResistanceBreak = 6,
//        PatternCompletion = 7
//    }

//    /// <summary>
//    /// Risk profile enumeration
//    /// </summary>
//    public enum RiskProfile
//    {
//        Conservative,
//        Moderate,
//        Aggressive
//    }

//    /// <summary>
//    /// Trade direction enumeration
//    /// </summary>
//    public enum TradeDirection
//    {
//        Neutral = 0,
//        Long = 1,
//        Short = -1
//    }

//    /// <summary>
//    /// Conviction level enumeration with integer values for comparison
//    /// </summary>
//    public enum ConvictionLevel
//    {
//        None = 0,
//        Low = 1,
//        Medium = 2,
//        High = 3,
//        VeryHigh = 4
//    }

//    /// <summary>
//    /// Signal category for classification
//    /// </summary>
//    public enum SignalCategory
//    {
//        Technical = 1,
//        Fundamental = 2,
//        Macro = 3,
//        Sentiment = 4,
//        Intermarket = 5,
//        Pattern = 6
//    }

//    /// <summary>
//    /// Timeframe enumeration
//    /// </summary>
//    public enum Timeframe
//    {
//        Minute1 = 1,
//        Minute5 = 5,
//        Minute15 = 15,
//        Minute30 = 30,
//        Hourly = 60,
//        FourHour = 240,
//        Daily = 1440,
//        Weekly = 10080,
//        Monthly = 43200
//    }

//    public class TradingSignal
//    {
//        public string Pair { get; set; }
//        public string Bias { get; set; }
//        public ConvictionLevel Conviction { get; set; }
//        public double Strength { get; set; }
//        public string Thesis { get; set; }
//        public double Entry { get; set; }
//        public double StopLoss { get; set; }
//        public double TakeProfit1 { get; set; }
//        public double TakeProfit2 { get; set; }
//        public double RiskReward { get; set; }
//        public double Rsi { get; set; }
//        public double Atr { get; set; }
//        public double Price { get; set; }
//        public int? Timeframes { get; set; }

//        public bool IsValid => !string.IsNullOrEmpty(Bias) &&
//                              Bias != "Neutral" &&
//                              Entry > 0 &&
//                              StopLoss > 0;

//        public int EntryPrice { get; internal set; }
//        public int StopLossPrice { get; internal set; }
//        public int TakeProfit1Price { get; internal set; }
//        public int RiskRewardRatio { get; internal set; }
//        public object ExpiresAt { get; internal set; }
//        public TradeDirection Direction { get; internal set; }
//        public decimal CurrentPrice { get; internal set; }
//        public int ConfirmingTimeframes { get; internal set; }
//        public decimal AtrValue { get; internal set; }

//        public override string ToString()
//        {
//            var tfInfo = Timeframes.HasValue ? $" ({Timeframes} TFs)" : "";
//            return $"{Pair}: {Bias} [{Conviction}]{tfInfo} - R:R {RiskReward:F2} | {Thesis}";
//        }

//        internal void AddReason(SignalReason signalReason)
//        {
//            throw new NotImplementedException();
//        }

//        internal void AddTimeframeSignal(Timeframe timeframe, TimeframeSignal signal)
//        {
//            throw new NotImplementedException();
//        }
//    }
//}
